### ISSUE TITLE
The `ModelName` property of `OllamaResource` should be public

### ISSUE THREAD

**Issue by aaronpowell** [MindscapeHQ/Raygun.Aspire.Hosting.Ollama#3]
I'm wanting to access the name of the model provided to the `OllamaResource` when you use this extension as a variable provided to other resources, but it is `internal`, meaning that I can't access it without relying on reflection.

Having this with a public `get` would mean that we can avoid having to define it in a local variable.

**Comment by QuantumNightmare** [comment]
Thanks for the PR to implement this. That's been merged and deployed on [NuGet as version 1.1.0](https://www.nuget.org/packages/Raygun.Aspire.Hosting.Ollama/1.1.0) now.
